FROM ubuntu:15.10

MAINTAINER Alexander Svyazin <guybrush@live.ru>

RUN apt-get update && apt-get install -y curl && curl -sL https://deb.nodesource.com/setup_4.x | bash - && apt-get install -y nodejs git && npm install -g elm
